### ISSUE TITLE
如何在win10下用vs编译

### ISSUE THREAD

**Issue by sui0312feng** [fpg2012/QuickOpenGL#1]
如何在win10下用vs编译

**Comment by fpg2012** [comment]
直接打开文件夹就行了，参考 https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170

~~Windows下会有些小错误，需要稍微调整一点点代码，有几个常量和win api的重名了~~ main分支最新的commit已经不需要调整代码了

记得编译完成后，需要把resource文件夹和`.frag`、`.vert`结尾的这堆shader复制到程序exe文件所在的目录

**Comment by fpg2012** [comment]
也可以使用命令行编译。

首先clone好仓库（姑且假设路径是`C:\QuickOpenGL`，然后打开Developer Powershell for Visual Studio，cd到仓库所在的路径

```
cd C:\QuickOpenGL
```

然后新建一个build文件夹

```
mkdir build
cd build
```

然后执行cmake，如果顺利会生成一堆vcxproj文件和一个sln文件，可以用于msbuild编译

```
cmake ..
```

然后执行msbuild

```
msbuild ALL_BUILD.vcxproj
```

执行完之后，`QuickOpenGL.exe`应该就在`build\debug`里面，把`resource`文件夹和shader复制进去

```
cd Debug
cp -r C:\QuickOpenGL\resource .
cp C:\QuickOpenGL\*.frag .
cp C:\QuickOpenGL\*.vert .
```

然后就可以运行QuickOpenGL.exe了，照理说可以看到这个画面

```
.\QuickOpenGL.exe
```

![image](https://github.com/user-attachments/assets/c08b7447-c2c8-4977-b057-06c7031ee1d0)

**Comment by sui0312feng** [comment]
OK
